### ISSUE TITLE
Packaging needs update

### ISSUE THREAD

**Issue by mih** [neurodebian/afni#1]
@Alexqw here is what debdiff things with respect to the current new packaging and the version last uploaded to NeuroDebian [debdiff.txt](https://github.com/neurodebian/afni/files/419976/debdiff.txt).

**Comment by aqw** [comment]
@hanke Skimming through quickly... that generally looks correct. The postinst file surprised me, but I don't see it in in my old repo. Could have been a stock one generated and shipped during build.

---Alex
