### ISSUE TITLE
"suma: command not found" on Ubuntu 16.04

### ISSUE THREAD

**Issue by zuooonz** [neurodebian/afni#10]
I am a new man using AFNI. And I  am facing a problem that SUMA doesn't work(`command not found`) on my Ubuntu(16.04) while AFNI seems to work well. I find others have the same problem: http://lists.alioth.debian.org/pipermail/neurodebian-users/2014-May/000802.html, but I don't know how to get out of it. It's very appreciated if someone can help me. Thanks a lot.

**Comment by zuooonz** [comment]
After ln: `sudo ln -i /usr/lib/afni/bin/suma /usr/bin/suma` then ran `suma` showed this error:
![screenshot from 2016-11-16 21-10-43](https://cloud.githubusercontent.com/assets/7878120/20348598/3853e2c0-ac41-11e6-9037-b7614ff0b769.png)
It's very appreciated if someone can help me. Thanks a lot.

**Comment by Youguang** [comment]
After ln: `sudo ln -i /usr/lib/afni/bin/suma /usr/binsuma` then `suma` showed this error:
![screenshot from 2016-11-16 21-10-43](https://cloud.githubusercontent.com/assets/7878120/20348598/3853e2c0-ac41-11e6-9037-b7614ff0b769.png)
It's very appreciated if someone can help me. Thanks a lot.

**Comment by yarikoptic** [comment]
Reproduced for me on my debian testing/sid.

@mih @aqw -- any time you could look into updating afni package which could possibly resolve this issue automagically?

@Youguang -- note that such manual symlinking is generally not advised.  Please (as in that email you pointed to) read  'man afni' to see how you should "enable" access to those all wonderful tools such as suma which are not by default in the PATH

**Comment by zuooonz** [comment]
@yarikoptic-private  Thanks for your help. Well, I change to Ubuntu 14.04.5, and `ln` really works. Besides, it works on Debian. Thank you anyway.

**Comment by yarikoptic** [comment]
was "resolved"
