### ISSUE TITLE
lib_vars_object.py is not installed in the package making many python scripts disfunctional

### ISSUE THREAD

**Issue by yarikoptic** [neurodebian/afni#3]
As reported by Jeffrey Mark Siskind (thanks)

``` shell

$> align_epi_anat.py
Traceback (most recent call last):
  File "/usr/lib/afni/bin/align_epi_anat.py", line 21, in <module>
    from db_mod import *
  File "/usr/lib/afni/bin/db_mod.py", line 13, in <module>
    import lib_vars_object as VO
ImportError: No module named lib_vars_object
```

resolving this issue should get accompanied with some basic at least smoke test to verify that python scripts are "runnable"

**Comment by yarikoptic** [comment]
for a smoke test thought to run -help but there are some special cases making it a bit cumbersome:
https://github.com/afni/afni/issues/46

**Comment by yarikoptic** [comment]
was resolved in -2 just uploaded

**Comment by aqw** [comment]
@yarikoptic Thanks for tracking all these down. Looks like there was a lot of fallout from the update and port to upstream's layout. :-/

---Alex

**Comment by yarikoptic** [comment]
That is why I can only reiterate that ideally we should try to advance upstream build setup :-)

**Comment by aqw** [comment]
@yarikoptic 100%. That's the next step. What Michael and I did was the first step. You're doing the next step (fixing the massive mess we made ;-)), and then we need to get this system upstream so this madness can /finally/ end. For all of us.

---Alex
